project:
  type: book
  output-dir: docs

book:
  title: "MYE References"
  chapters:
    - index.qmd
    - resources.qmd 
    - part: R.qmd
      chapters: 
      - R_datamanage.qmd
      - R_dataviz.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    code-overflow: scroll 

editor: source

