
# Regular Expressions 

## Select/Remove Items

### Select 

```{r}
thispatternexample <- "example1"
patternexample     <- "example2"
thispattern        <- "example3"

mget(ls(pattern = "pattern"))  #pattern included within (*pattern*)
mget(ls(pattern = "^pattern")) #starts with pattern 
mget(ls(pattern = "pattern$")) #ends with pattern
```

### Remove

```{r, eval = FALSE }
rm(list = ls(pattern = "pattern"))
rm(list = ls(pattern = "^prefix\\."))
rm(list = ls(pattern = "suffix$"))
```

### Special Characters (like `.`)

```{r}
df.1_toprows   <- mtcars[1:2,]
df.2_middle    <- mtcars[3:4,]
df.3_otherrows <- mtcars[5:6, ] 
df4other        <- mtcars[7:8,]

mget(ls(pattern="^df"))
mget(ls(pattern="^df.")) #ignores . (need to denote special character)
mget(ls(pattern="^df\\.")) # use double slash for special character

# can use bind_rows to combine all df's (if they are the same variables) 
dplyr::bind_rows(mget(ls(pattern="^df\\.")))
```


## Links 


- [Stack Overflow | Multiple pattern Matching in R](https://stackoverflow.com/questions/24035057/multiple-pattern-matching-in-r)
- [Stack Overflow | R regex to match beginning and end of string, ignoring middle](https://stackoverflow.com/questions/50668761/r-regex-to-match-beginning-and-end-of-string-ignoring-middle)
- [Stack Overflow | regex - How to match a string and white space in R](https://stackoverflow.com/questions/38392493/how-to-match-a-string-and-white-space-in-r)
