
# R Shiny

**Links** 

- [Shiny | Tutorial - Lesson 1 Welcome to Shiny](https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/)
- [MAPS Project | Example of styling in R Shiny](https://sicdata.shinyapps.io/MAPS-dash/) 
- [Stack Overflow |  Background color of tabs in shiny tabPanel](https://stackoverflow.com/questions/35025145/background-color-of-tabs-in-shiny-tabpanel)
- [Stack Overflow | Dashboard date in a shiny app deployed in shinyapps.io](https://stackoverflow.com/questions/61764764/r-dashboard-date-in-a-shiny-app-deployed-in-shinyapps-io)
- [Stack Overflow | Change font and color in helpText()](https://stackoverflow.com/questions/59292157/change-font-and-color-in-helptext)
- [Stack Overflow | What are the default font sizes (in pixels) for the html heading tags (<h1>, <h2>, <h3>, etc.)?](https://stackoverflow.com/questions/5410066/what-are-the-default-font-sizes-in-pixels-for-the-html-heading-tags-h1-h2)
- [GitHub ropensci/plotly | renderPlotly() does not accept NULL values · Issue #1116](https://github.com/plotly/plotly.R/issues/1116)
- [UofT Coders | Making interactive plots using Shiny in R](https://uoftcoders.github.io/studyGroup/lessons/r/shiny/lesson/)
- [Stack Overflow | How to disable a tabPanel in shinydashboard?](https://stackoverflow.com/questions/37382091/how-to-disable-a-tabpanel-in-shinydashboard)
- [Stack Overflow | Print Shiny App Screen not working Error: shinyjs: extendShinyjs: `functions` argument must be provided](https://stackoverflow.com/questions/63860952/print-shiny-app-screen-not-working-error-shinyjs-extendshinyjs-functions-ar) 
- [Stack Overflow | Button extension to download all data or only visible data](https://stackoverflow.com/questions/50508854/button-extension-to-download-all-data-or-only-visible-data)
- [Shiny | Help users download data from your app](https://shiny.rstudio.com/articles/download.html)
- [Shiny | Change the value of a number input on the client — updateNumericInput](https://shiny.rstudio.com/reference/shiny/latest/updateNumericInput.html)
- [Stack Overflow | Label position, textInput](https://stackoverflow.com/questions/44784083/shiny-label-position-textinput)
- [RStudio Community | Problem in downloading the plot with downloadhandler for shiny app - shiny](https://community.rstudio.com/t/problem-in-downloading-the-plot-with-downloadhandler-for-shiny-app/44876/2)
- [Stack Overflow | Download Handler with reactive datatable (R Shiny)](https://community.rstudio.com/t/problem-in-downloading-the-plot-with-downloadhandler-for-shiny-app/44876/2)
- [Stack Overflow | How do you change the color of an icon in an R Shiny app?](https://stackoverflow.com/questions/46531607/how-do-you-change-the-color-of-an-icon-in-an-r-shiny-app)
- [Stack Overflow](Save plots made in a shiny app])https://stackoverflow.com/questions/14810409/how-to-save-plots-that-are-made-in-a-shiny-app
- [Stack Overflow | Downloading png from Shiny (R)](https://stackoverflow.com/questions/26764481/downloading-png-from-shiny-r)
- [Using the downloadablePlot Shiny Module](https://cran.r-project.org/web/packages/periscope/vignettes/downloadablePlot-module.html)
- [Mastering Shiny Solutions | Chapter 9 Uploads and Downloads](https://mastering-shiny-solutions.org/uploads-and-downloads.html)
- [Stack Overflow | Put ordered list in a table row <tr>. Is it possible?](https://stackoverflow.com/questions/21280254/put-ordered-list-in-a-table-row-tr-is-it-possible)
- [WebDeveloper | How to use Numbered Lists inside HTML tables](https://forum.webdeveloper.com/d/225252-how-to-use-numbered-lists-inside-html-tables/8)
- [Stack Overflow | How to add css tag to SideBarPanel in Shiny App (R)](https://stackoverflow.com/questions/23299345/how-to-add-css-tag-to-sidebarpanel-in-shiny-app-r)
- [Stack Overflow | R Shiny: Unable to dispatch task for application, there are 1 tasks in progress](https://stackoverflow.com/questions/45469978/r-shiny-unable-to-dispatch-task-for-application-there-are-1-tasks-in-progress)
- [RStudio | Shiny in production: Principles, practices, and tools](https://www.rstudio.com/resources/rstudioconf-2019/shiny-in-production-principles-practices-and-tools/)
- [StackOverflow | ggplot2 and Shiny: how to scale the size of legend with figure size?](https://stackoverflow.com/questions/34274531/ggplot2-and-shiny-how-to-scale-the-size-of-legend-with-figure-size)
- [Stack Overflow | how to center box div element directly in center?](https://stackoverflow.com/questions/1725759/css-how-to-center-box-div-element-directly-in-center)
- [Stack Overflow | pickerInput font or background color](https://stackoverflow.com/questions/54081254/pickerinput-font-or-background-color)
- [Outstanding User Interfaces with Shiny | Chapter 8 Beautify with {fresh}](https://unleash-shiny.rinterface.com/beautify-with-fresh.html)
- [Stack Overflow | Change colour of checkbox using shinyWidgets](https://stackoverflow.com/questions/53850152/change-colour-of-checkbox-using-shinywidgets)
- [RStudio {shinydashboard} | Customizing dashboard appearance](https://rstudio.github.io/shinydashboard/appearance.html#css)
- [SoundCode | Customize Radio Button Appearance with CSS](https://shop.mysoda.eu/en/collections/hiilihapotuslaitteet/products/woody-combo-1) 
- [Stack Overflow | Is it possible to change the color of selected radio button's center circle](https://stackoverflow.com/questions/23167637/is-it-possible-to-change-the-color-of-selected-radio-buttons-center-circle/23167781#23167781) 
- [Stack Overflow | R shiny: change colour of individual check boxes in checkboxGroupInput](https://stackoverflow.com/questions/62460722/r-shiny-change-colour-of-individual-check-boxes-in-checkboxgroupinput)
- [Stack Overflow | Is it possible to change the color of progressBar() in ShinyWidgets to a custom color>](https://stackoverflow.com/questions/49494891/is-it-possible-to-change-the-color-of-progressbar-in-shinywidgets-to-a-custom)
- [dreamRs/shinyWidgets | checkboxGroupButtons color change on press · Issue #335](https://github.com/dreamRs/shinyWidgets/issues/335)
- [dreamRs/shinyWidgets | Change colors outside the pre-defined ones · Issue #276](https://github.com/dreamRs/shinyWidgets/issues/276) 
- [dreamRs/shinyWidgets | change color in css · Issue #59](https://github.com/dreamRs/shinyWidgets/issues/59)
- [rstudio/DT | display Inf as Inf not like NA · Issue #496](https://github.com/rstudio/DT/issues/496) 
- [DataTables | Type detection plug-ins](https://datatables.net/plug-ins/type-detection/)
- [RStudio Community | How to disable download button in shiny until user uploads the data - shiny](https://community.rstudio.com/t/how-to-disable-download-button-in-shiny-until-user-uploads-the-data/28854/2)
- [Stack Overflow | shiny app : disable downloadbutton](https://stackoverflow.com/questions/25247852/shiny-app-disable-downloadbutton)
- [Stack Overflow | How to disable button based on a condition in a R Markdown document with shiny elements?](https://stackoverflow.com/questions/43292755/how-to-disable-button-based-on-a-condition-in-a-r-markdown-document-with-shiny-e) 
- [listendata | Add Loader for Shiny R](https://www.listendata.com/2019/07/add-loader-for-shiny-r.html)
- [{shinycssloaders} package 1.0.0](https://daattali.com/shiny/shinycssloaders-demo/)
- [daattali/shinycssloaders | Add loading animations to a Shiny output while it's recalculating](https://github.com/daattali/shinycssloaders)
- [mrismailt/r-shiny-dockerfile-template | Template for containerizing R Shiny using Docker](https://github.com/mrismailt/r-shiny-dockerfile-template)
- [Massoud Mazar | Show progress bar when pre-loading data in Shiny app](https://www.mazsoft.com/blog/post/2018/01/01/show-progress-bar-when-pre-loading-data-in-shiny-app)
-[RStudio Community | The application failed to start - Error in value\[\[3L\]\](cond) : RStudio not running](https://community.rstudio.com/t/the-application-failed-to-start-error-in-value-3l-cond-rstudio-not-running/15309)
- [Jiwan Heo | Pass around data between Shiny modules with R6](https://jiwanheo.rbind.io/post/2022-02-06-pass-around-data-between-shiny-modules-with-r6/)


*iframe sizing*  

- [James Fisher | How do I make a full-width `iframe` with fixed aspect ratio?](https://jameshfisher.com/2017/08/30/how-do-i-make-a-full-width-iframe/)
- [Stack Overflow | Make iframe automatically adjust height according to the contents without using scrollbar?](https://stackoverflow.com/questions/9975810/make-iframe-automatically-adjust-height-according-to-the-contents-without-using)
- [Stack Overflow | How to set iframe size dynamically](https://stackoverflow.com/questions/7317781/how-to-set-iframe-size-dynamically)  

*{DT} in Shiny*  

- [RStudio DT | An R interface to the DataTables library](https://rstudio.github.io/DT/)
- [RStudio DT | DataTables Options](https://rstudio.github.io/DT/options.html)
- [RStudio DT | Helper Functions](https://rstudio.github.io/DT/functions.html)
- [Rstudio DT | Using DT in Shiny](https://rstudio.github.io/DT/shiny.html)
- [Stack Overflow | Column alignment in DT datatable](https://stackoverflow.com/questions/35749389/column-alignment-in-dt-datatable) 
- [Stack Overflow | Add download buttons in DT::renderDataTable](https://stackoverflow.com/questions/50039186/add-download-buttons-in-dtrenderdatatable)
- [GitHub rstudio/DT | Downloading all the data using Buttons extension · Issue #267](https://github.com/rstudio/DT/issues/267)
- [datatables.net | dom - define table control elements](https://datatables.net/reference/option/dom) 
- [Stack Overflow | Change filename when downloading data from datatable R](https://stackoverflow.com/questions/56275928/change-filename-when-downloading-data-from-datatable-r)  
- [Stack Overflow | How to make datatable ellipsis plugin work with full data download button?](https://stackoverflow.com/questions/61195139/how-to-make-datatable-ellipsis-plugin-work-with-full-data-download-button)
- [DataTables | example - Format output data - export options](https://datatables.net/extensions/buttons/examples/html5/outputFormat-function.html)
- [Stack Overflow | Title export options of DT::datatable using shiny app](https://stackoverflow.com/questions/57885108/title-export-options-of-dtdatatable-using-shiny-app)  
- [Stack Overflow | dataframe - R: Assign variable labels of data frame columns](https://stackoverflow.com/questions/25205410/r-shiny-set-datatable-column-width)  
- [Stack Overflow | R Shiny set DataTable column width](https://stackoverflow.com/questions/44101055/changing-font-size-in-r-datatables-dt)  
- [Stack Overflow | formatting - changing font size in R DataTables (DT)](https://stackoverflow.com/questions/44101055/changing-font-size-in-r-datatables-dt) 
- [Yihui Shiny Apps | DataTables Information](https://yihui.shinyapps.io/DT-info/)
- [Stack Overflow | how to remove padding in datatable column](https://stackoverflow.com/questions/51472196/how-to-remove-padding-in-datatable-column)
- [Pierre Rebours's Log | Custom sorting with DT](https://www.pierrerebours.com/2017/09/custom-sorting-with-dt.html)

*{shinyWidgets}*  

- [{shinyWidgets} | Numeric Range Input — numericRangeInput](https://dreamrs.github.io/shinyWidgets/reference/numericRangeInput.html)  
- [{shinyWidgets} | Select picker Input Control — pickerInput](https://dreamrs.github.io/shinyWidgets/reference/pickerInput.html)
- [{shinyWidgers} | Options for `pickerInput` — pickerOptions](https://dreamrs.github.io/shinyWidgets/reference/pickerOptions.html)
- [Stack Overflow | How do I change the height of picker input in from shinywidget?](https://stackoverflow.com/questions/59248310/how-do-i-change-the-height-of-picker-input-in-from-shinywidget)  
- [Stack Overflow | How to text wrap selected values in a pickerInput (from shinyWidgets package). Make the height of the selector change as to accommodate multiple lines](https://stackoverflow.com/questions/56774922/how-to-text-wrap-selected-values-in-a-pickerinput-from-shinywidgets-package-m)  
- [Stack Overflow |How to text wrap choices from a pickerInput, If the length of the choices are long the choices often end up outside the screen](https://stackoverflow.com/questions/51355878/how-to-text-wrap-choices-from-a-pickerinput-if-the-length-of-the-choices-are-lo/51406191#51406191)
- [Stack Overflow | How to change the container color of a pickerInput element?](https://stackoverflow.com/questions/58124453/how-to-change-the-container-color-of-a-pickerinput-element)

*shiny widgets*  

- [RStudio Community | selectInput size - shiny](https://community.rstudio.com/t/selectinput-size/2402)
- [Shiny | Selectize Examples](https://shiny.rstudio.com/gallery/selectize-examples.html)
- [Stack Overflow | checkboxGroupInput - select all checkboxes by click](https://stackoverflow.com/questions/28829682/r-shiny-checkboxgroupinput-select-all-checkboxes-by-click)
- [R Documention | {shinyWidgets}::radioGroupButtons - buttons group radio input control](https://www.rdocumentation.org/packages/shinyWidgets/versions/0.5.4/topics/radioGroupButtons)
- [Stack Overflow | Non-Slider Numeric Range Input](https://stackoverflow.com/questions/49395482/non-slider-numeric-range-input)